# fly.toml app configuration file generated for youinc on 2026-07-05T05:29:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'youinc'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[[mounts]]
  source = 'youinc_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
