/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WidgetsRouteImport } from './routes/widgets'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as StartRouteImport } from './routes/start'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as CustomBuildsRouteImport } from './routes/custom-builds'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as SignupIndexRouteImport } from './routes/signup.index'
import { Route as SigninIndexRouteImport } from './routes/signin.index'
import { Route as WorkspaceSettingsRouteImport } from './routes/workspace.settings'
import { Route as SignupPasswordRouteImport } from './routes/signup.password'
import { Route as SignupNameRouteImport } from './routes/signup.name'
import { Route as SignupCredentialRouteImport } from './routes/signup.credential'
import { Route as SigninPasswordRouteImport } from './routes/signin.password'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as ApiAnalyticsRouteImport } from './routes/api.analytics'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiCronTrialRemindersRouteImport } from './routes/api.cron.trial-reminders'
import { Route as ApiAkahuCallbackRouteImport } from './routes/api.akahu.callback'
import { Route as ApiAkahuOauthStartRouteImport } from './routes/api.akahu.oauth.start'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsRoute = WidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomBuildsRoute = CustomBuildsRouteImport.update({
  id: '/custom-builds',
  path: '/custom-builds',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignupRoute,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SigninRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const SignupPasswordRoute = SignupPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => SignupRoute,
} as any)
const SignupNameRoute = SignupNameRouteImport.update({
  id: '/name',
  path: '/name',
  getParentRoute: () => SignupRoute,
} as any)
const SignupCredentialRoute = SignupCredentialRouteImport.update({
  id: '/credential',
  path: '/credential',
  getParentRoute: () => SignupRoute,
} as any)
const SigninPasswordRoute = SigninPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => SigninRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTrialRemindersRoute = ApiCronTrialRemindersRouteImport.update({
  id: '/api/cron/trial-reminders',
  path: '/api/cron/trial-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAkahuCallbackRoute = ApiAkahuCallbackRouteImport.update({
  id: '/api/akahu/callback',
  path: '/api/akahu/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAkahuOauthStartRoute = ApiAkahuOauthStartRouteImport.update({
  id: '/api/akahu/oauth/start',
  path: '/api/akahu/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/custom-builds': typeof CustomBuildsRoute
  '/data-deletion': typeof DataDeletionRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/integrations': typeof IntegrationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/signin': typeof SigninRouteWithChildren
  '/signup': typeof SignupRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/widgets': typeof WidgetsRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/signin/password': typeof SigninPasswordRoute
  '/signup/credential': typeof SignupCredentialRoute
  '/signup/name': typeof SignupNameRoute
  '/signup/password': typeof SignupPasswordRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/signin/': typeof SigninIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/api/akahu/callback': typeof ApiAkahuCallbackRoute
  '/api/cron/trial-reminders': typeof ApiCronTrialRemindersRoute
  '/api/akahu/oauth/start': typeof ApiAkahuOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/custom-builds': typeof CustomBuildsRoute
  '/data-deletion': typeof DataDeletionRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/integrations': typeof IntegrationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/widgets': typeof WidgetsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/signin/password': typeof SigninPasswordRoute
  '/signup/credential': typeof SignupCredentialRoute
  '/signup/name': typeof SignupNameRoute
  '/signup/password': typeof SignupPasswordRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/signin': typeof SigninIndexRoute
  '/signup': typeof SignupIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/api/akahu/callback': typeof ApiAkahuCallbackRoute
  '/api/cron/trial-reminders': typeof ApiCronTrialRemindersRoute
  '/api/akahu/oauth/start': typeof ApiAkahuOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/custom-builds': typeof CustomBuildsRoute
  '/data-deletion': typeof DataDeletionRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/integrations': typeof IntegrationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/signin': typeof SigninRouteWithChildren
  '/signup': typeof SignupRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/widgets': typeof WidgetsRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/signin/password': typeof SigninPasswordRoute
  '/signup/credential': typeof SignupCredentialRoute
  '/signup/name': typeof SignupNameRoute
  '/signup/password': typeof SignupPasswordRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/signin/': typeof SigninIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/api/akahu/callback': typeof ApiAkahuCallbackRoute
  '/api/cron/trial-reminders': typeof ApiCronTrialRemindersRoute
  '/api/akahu/oauth/start': typeof ApiAkahuOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/changelog'
    | '/compare'
    | '/contact'
    | '/custom-builds'
    | '/data-deletion'
    | '/demo'
    | '/docs'
    | '/help'
    | '/integrations'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/roadmap'
    | '/security'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/start'
    | '/status'
    | '/terms'
    | '/use-cases'
    | '/widgets'
    | '/workspace'
    | '/admin/analytics'
    | '/admin/feedback'
    | '/api/analytics'
    | '/auth/confirm'
    | '/signin/password'
    | '/signup/credential'
    | '/signup/name'
    | '/signup/password'
    | '/workspace/settings'
    | '/signin/'
    | '/signup/'
    | '/workspace/'
    | '/api/akahu/callback'
    | '/api/cron/trial-reminders'
    | '/api/akahu/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changelog'
    | '/compare'
    | '/contact'
    | '/custom-builds'
    | '/data-deletion'
    | '/demo'
    | '/docs'
    | '/help'
    | '/integrations'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/roadmap'
    | '/security'
    | '/sitemap.xml'
    | '/start'
    | '/status'
    | '/terms'
    | '/use-cases'
    | '/widgets'
    | '/admin/analytics'
    | '/admin/feedback'
    | '/api/analytics'
    | '/auth/confirm'
    | '/signin/password'
    | '/signup/credential'
    | '/signup/name'
    | '/signup/password'
    | '/workspace/settings'
    | '/signin'
    | '/signup'
    | '/workspace'
    | '/api/akahu/callback'
    | '/api/cron/trial-reminders'
    | '/api/akahu/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/changelog'
    | '/compare'
    | '/contact'
    | '/custom-builds'
    | '/data-deletion'
    | '/demo'
    | '/docs'
    | '/help'
    | '/integrations'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/roadmap'
    | '/security'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/start'
    | '/status'
    | '/terms'
    | '/use-cases'
    | '/widgets'
    | '/workspace'
    | '/admin/analytics'
    | '/admin/feedback'
    | '/api/analytics'
    | '/auth/confirm'
    | '/signin/password'
    | '/signup/credential'
    | '/signup/name'
    | '/signup/password'
    | '/workspace/settings'
    | '/signin/'
    | '/signup/'
    | '/workspace/'
    | '/api/akahu/callback'
    | '/api/cron/trial-reminders'
    | '/api/akahu/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChangelogRoute: typeof ChangelogRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CustomBuildsRoute: typeof CustomBuildsRoute
  DataDeletionRoute: typeof DataDeletionRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRoute
  HelpRoute: typeof HelpRoute
  IntegrationsRoute: typeof IntegrationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RoadmapRoute: typeof RoadmapRoute
  SecurityRoute: typeof SecurityRoute
  SigninRoute: typeof SigninRouteWithChildren
  SignupRoute: typeof SignupRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartRoute: typeof StartRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  UseCasesRoute: typeof UseCasesRoute
  WidgetsRoute: typeof WidgetsRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  ApiAkahuCallbackRoute: typeof ApiAkahuCallbackRoute
  ApiCronTrialRemindersRoute: typeof ApiCronTrialRemindersRoute
  ApiAkahuOauthStartRoute: typeof ApiAkahuOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets': {
      id: '/widgets'
      path: '/widgets'
      fullPath: '/widgets'
      preLoaderRoute: typeof WidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-builds': {
      id: '/custom-builds'
      path: '/custom-builds'
      fullPath: '/custom-builds'
      preLoaderRoute: typeof CustomBuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/signup/': {
      id: '/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signin/': {
      id: '/signin/'
      path: '/'
      fullPath: '/signin/'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof SigninRoute
    }
    '/workspace/settings': {
      id: '/workspace/settings'
      path: '/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/signup/password': {
      id: '/signup/password'
      path: '/password'
      fullPath: '/signup/password'
      preLoaderRoute: typeof SignupPasswordRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/name': {
      id: '/signup/name'
      path: '/name'
      fullPath: '/signup/name'
      preLoaderRoute: typeof SignupNameRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/credential': {
      id: '/signup/credential'
      path: '/credential'
      fullPath: '/signup/credential'
      preLoaderRoute: typeof SignupCredentialRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signin/password': {
      id: '/signin/password'
      path: '/password'
      fullPath: '/signin/password'
      preLoaderRoute: typeof SigninPasswordRouteImport
      parentRoute: typeof SigninRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/trial-reminders': {
      id: '/api/cron/trial-reminders'
      path: '/api/cron/trial-reminders'
      fullPath: '/api/cron/trial-reminders'
      preLoaderRoute: typeof ApiCronTrialRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/akahu/callback': {
      id: '/api/akahu/callback'
      path: '/api/akahu/callback'
      fullPath: '/api/akahu/callback'
      preLoaderRoute: typeof ApiAkahuCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/akahu/oauth/start': {
      id: '/api/akahu/oauth/start'
      path: '/api/akahu/oauth/start'
      fullPath: '/api/akahu/oauth/start'
      preLoaderRoute: typeof ApiAkahuOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SigninRouteChildren {
  SigninPasswordRoute: typeof SigninPasswordRoute
  SigninIndexRoute: typeof SigninIndexRoute
}

const SigninRouteChildren: SigninRouteChildren = {
  SigninPasswordRoute: SigninPasswordRoute,
  SigninIndexRoute: SigninIndexRoute,
}

const SigninRouteWithChildren =
  SigninRoute._addFileChildren(SigninRouteChildren)

interface SignupRouteChildren {
  SignupCredentialRoute: typeof SignupCredentialRoute
  SignupNameRoute: typeof SignupNameRoute
  SignupPasswordRoute: typeof SignupPasswordRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupCredentialRoute: SignupCredentialRoute,
  SignupNameRoute: SignupNameRoute,
  SignupPasswordRoute: SignupPasswordRoute,
  SignupIndexRoute: SignupIndexRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChangelogRoute: ChangelogRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CustomBuildsRoute: CustomBuildsRoute,
  DataDeletionRoute: DataDeletionRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRoute,
  HelpRoute: HelpRoute,
  IntegrationsRoute: IntegrationsRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RoadmapRoute: RoadmapRoute,
  SecurityRoute: SecurityRoute,
  SigninRoute: SigninRouteWithChildren,
  SignupRoute: SignupRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartRoute: StartRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  UseCasesRoute: UseCasesRoute,
  WidgetsRoute: WidgetsRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  ApiAkahuCallbackRoute: ApiAkahuCallbackRoute,
  ApiCronTrialRemindersRoute: ApiCronTrialRemindersRoute,
  ApiAkahuOauthStartRoute: ApiAkahuOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
