/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetsRouteImport } from './routes/widgets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomBuildsRouteImport } from './routes/custom-builds'
import { Route as IndexRouteImport } from './routes/index'

const WidgetsRoute = WidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomBuildsRoute = CustomBuildsRouteImport.update({
  id: '/custom-builds',
  path: '/custom-builds',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom-builds': typeof CustomBuildsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/widgets': typeof WidgetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-builds': typeof CustomBuildsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/widgets': typeof WidgetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom-builds': typeof CustomBuildsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/widgets': typeof WidgetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom-builds'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/widgets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/custom-builds' | '/dashboard' | '/demo' | '/login' | '/widgets'
  id:
    | '__root__'
    | '/'
    | '/custom-builds'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/widgets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomBuildsRoute: typeof CustomBuildsRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  WidgetsRoute: typeof WidgetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widgets': {
      id: '/widgets'
      path: '/widgets'
      fullPath: '/widgets'
      preLoaderRoute: typeof WidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-builds': {
      id: '/custom-builds'
      path: '/custom-builds'
      fullPath: '/custom-builds'
      preLoaderRoute: typeof CustomBuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomBuildsRoute: CustomBuildsRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  WidgetsRoute: WidgetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
