/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup.index'
import { Route as SigninIndexRouteImport } from './routes/signin.index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as WorkspaceSplatRouteImport } from './routes/workspace.$'
import { Route as SignupPasswordRouteImport } from './routes/signup.password'
import { Route as SignupNameRouteImport } from './routes/signup.name'
import { Route as SignupCredentialRouteImport } from './routes/signup.credential'
import { Route as SigninPasswordRouteImport } from './routes/signin.password'
import { Route as DemoSpendingRouteImport } from './routes/demo.spending'
import { Route as DemoNetWorthRouteImport } from './routes/demo.net-worth'
import { Route as DemoActivityRouteImport } from './routes/demo.activity'
import { Route as DemoAccountsRouteImport } from './routes/demo.accounts'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AppWorkshopRouteImport } from './routes/app.workshop'
import { Route as AppSpendingRouteImport } from './routes/app.spending'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPinboardRouteImport } from './routes/app.pinboard'
import { Route as AppNetWorthRouteImport } from './routes/app.net-worth'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'
import { Route as ApiAnalyticsRouteImport } from './routes/api.analytics'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiAkahuCallbackRouteImport } from './routes/api.akahu.callback'
import { Route as ApiAkahuOauthStartRouteImport } from './routes/api.akahu.oauth.start'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignupRoute,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SigninRoute,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const WorkspaceSplatRoute = WorkspaceSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => WorkspaceRoute,
} as any)
const SignupPasswordRoute = SignupPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => SignupRoute,
} as any)
const SignupNameRoute = SignupNameRouteImport.update({
  id: '/name',
  path: '/name',
  getParentRoute: () => SignupRoute,
} as any)
const SignupCredentialRoute = SignupCredentialRouteImport.update({
  id: '/credential',
  path: '/credential',
  getParentRoute: () => SignupRoute,
} as any)
const SigninPasswordRoute = SigninPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => SigninRoute,
} as any)
const DemoSpendingRoute = DemoSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => DemoRoute,
} as any)
const DemoNetWorthRoute = DemoNetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => DemoRoute,
} as any)
const DemoActivityRoute = DemoActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAccountsRoute = DemoAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DemoRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkshopRoute = AppWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => AppRoute,
} as any)
const AppSpendingRoute = AppSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPinboardRoute = AppPinboardRouteImport.update({
  id: '/pinboard',
  path: '/pinboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNetWorthRoute = AppNetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAkahuCallbackRoute = ApiAkahuCallbackRouteImport.update({
  id: '/api/akahu/callback',
  path: '/api/akahu/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAkahuOauthStartRoute = ApiAkahuOauthStartRouteImport.update({
  id: '/api/akahu/oauth/start',
  path: '/api/akahu/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRouteWithChildren
  '/signup': typeof SignupRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/net-worth': typeof AppNetWorthRoute
  '/app/pinboard': typeof AppPinboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spending': typeof AppSpendingRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/demo/accounts': typeof DemoAccountsRoute
  '/demo/activity': typeof DemoActivityRoute
  '/demo/net-worth': typeof DemoNetWorthRoute
  '/demo/spending': typeof DemoSpendingRoute
  '/signin/password': typeof SigninPasswordRoute
  '/signup/credential': typeof SignupCredentialRoute
  '/signup/name': typeof SignupNameRoute
  '/signup/password': typeof SignupPasswordRoute
  '/workspace/$': typeof WorkspaceSplatRoute
  '/app/': typeof AppIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/api/akahu/callback': typeof ApiAkahuCallbackRoute
  '/api/akahu/oauth/start': typeof ApiAkahuOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/net-worth': typeof AppNetWorthRoute
  '/app/pinboard': typeof AppPinboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spending': typeof AppSpendingRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/demo/accounts': typeof DemoAccountsRoute
  '/demo/activity': typeof DemoActivityRoute
  '/demo/net-worth': typeof DemoNetWorthRoute
  '/demo/spending': typeof DemoSpendingRoute
  '/signin/password': typeof SigninPasswordRoute
  '/signup/credential': typeof SignupCredentialRoute
  '/signup/name': typeof SignupNameRoute
  '/signup/password': typeof SignupPasswordRoute
  '/workspace/$': typeof WorkspaceSplatRoute
  '/app': typeof AppIndexRoute
  '/demo': typeof DemoIndexRoute
  '/signin': typeof SigninIndexRoute
  '/signup': typeof SignupIndexRoute
  '/api/akahu/callback': typeof ApiAkahuCallbackRoute
  '/api/akahu/oauth/start': typeof ApiAkahuOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRouteWithChildren
  '/signup': typeof SignupRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/net-worth': typeof AppNetWorthRoute
  '/app/pinboard': typeof AppPinboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spending': typeof AppSpendingRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/demo/accounts': typeof DemoAccountsRoute
  '/demo/activity': typeof DemoActivityRoute
  '/demo/net-worth': typeof DemoNetWorthRoute
  '/demo/spending': typeof DemoSpendingRoute
  '/signin/password': typeof SigninPasswordRoute
  '/signup/credential': typeof SignupCredentialRoute
  '/signup/name': typeof SignupNameRoute
  '/signup/password': typeof SignupPasswordRoute
  '/workspace/$': typeof WorkspaceSplatRoute
  '/app/': typeof AppIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/api/akahu/callback': typeof ApiAkahuCallbackRoute
  '/api/akahu/oauth/start': typeof ApiAkahuOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/docs'
    | '/help'
    | '/onboarding'
    | '/privacy'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/workspace'
    | '/admin/analytics'
    | '/api/analytics'
    | '/app/accounts'
    | '/app/activity'
    | '/app/net-worth'
    | '/app/pinboard'
    | '/app/settings'
    | '/app/spending'
    | '/app/workshop'
    | '/auth/confirm'
    | '/demo/accounts'
    | '/demo/activity'
    | '/demo/net-worth'
    | '/demo/spending'
    | '/signin/password'
    | '/signup/credential'
    | '/signup/name'
    | '/signup/password'
    | '/workspace/$'
    | '/app/'
    | '/demo/'
    | '/signin/'
    | '/signup/'
    | '/api/akahu/callback'
    | '/api/akahu/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/help'
    | '/onboarding'
    | '/privacy'
    | '/sitemap.xml'
    | '/workspace'
    | '/admin/analytics'
    | '/api/analytics'
    | '/app/accounts'
    | '/app/activity'
    | '/app/net-worth'
    | '/app/pinboard'
    | '/app/settings'
    | '/app/spending'
    | '/app/workshop'
    | '/auth/confirm'
    | '/demo/accounts'
    | '/demo/activity'
    | '/demo/net-worth'
    | '/demo/spending'
    | '/signin/password'
    | '/signup/credential'
    | '/signup/name'
    | '/signup/password'
    | '/workspace/$'
    | '/app'
    | '/demo'
    | '/signin'
    | '/signup'
    | '/api/akahu/callback'
    | '/api/akahu/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/docs'
    | '/help'
    | '/onboarding'
    | '/privacy'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/workspace'
    | '/admin/analytics'
    | '/api/analytics'
    | '/app/accounts'
    | '/app/activity'
    | '/app/net-worth'
    | '/app/pinboard'
    | '/app/settings'
    | '/app/spending'
    | '/app/workshop'
    | '/auth/confirm'
    | '/demo/accounts'
    | '/demo/activity'
    | '/demo/net-worth'
    | '/demo/spending'
    | '/signin/password'
    | '/signup/credential'
    | '/signup/name'
    | '/signup/password'
    | '/workspace/$'
    | '/app/'
    | '/demo/'
    | '/signin/'
    | '/signup/'
    | '/api/akahu/callback'
    | '/api/akahu/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  DocsRoute: typeof DocsRoute
  HelpRoute: typeof HelpRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SigninRoute: typeof SigninRouteWithChildren
  SignupRoute: typeof SignupRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  ApiAkahuCallbackRoute: typeof ApiAkahuCallbackRoute
  ApiAkahuOauthStartRoute: typeof ApiAkahuOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signin/': {
      id: '/signin/'
      path: '/'
      fullPath: '/signin/'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof SigninRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/workspace/$': {
      id: '/workspace/$'
      path: '/$'
      fullPath: '/workspace/$'
      preLoaderRoute: typeof WorkspaceSplatRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/signup/password': {
      id: '/signup/password'
      path: '/password'
      fullPath: '/signup/password'
      preLoaderRoute: typeof SignupPasswordRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/name': {
      id: '/signup/name'
      path: '/name'
      fullPath: '/signup/name'
      preLoaderRoute: typeof SignupNameRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/credential': {
      id: '/signup/credential'
      path: '/credential'
      fullPath: '/signup/credential'
      preLoaderRoute: typeof SignupCredentialRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signin/password': {
      id: '/signin/password'
      path: '/password'
      fullPath: '/signin/password'
      preLoaderRoute: typeof SigninPasswordRouteImport
      parentRoute: typeof SigninRoute
    }
    '/demo/spending': {
      id: '/demo/spending'
      path: '/spending'
      fullPath: '/demo/spending'
      preLoaderRoute: typeof DemoSpendingRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/net-worth': {
      id: '/demo/net-worth'
      path: '/net-worth'
      fullPath: '/demo/net-worth'
      preLoaderRoute: typeof DemoNetWorthRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/activity': {
      id: '/demo/activity'
      path: '/activity'
      fullPath: '/demo/activity'
      preLoaderRoute: typeof DemoActivityRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/accounts': {
      id: '/demo/accounts'
      path: '/accounts'
      fullPath: '/demo/accounts'
      preLoaderRoute: typeof DemoAccountsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workshop': {
      id: '/app/workshop'
      path: '/workshop'
      fullPath: '/app/workshop'
      preLoaderRoute: typeof AppWorkshopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spending': {
      id: '/app/spending'
      path: '/spending'
      fullPath: '/app/spending'
      preLoaderRoute: typeof AppSpendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pinboard': {
      id: '/app/pinboard'
      path: '/pinboard'
      fullPath: '/app/pinboard'
      preLoaderRoute: typeof AppPinboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/net-worth': {
      id: '/app/net-worth'
      path: '/net-worth'
      fullPath: '/app/net-worth'
      preLoaderRoute: typeof AppNetWorthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/akahu/callback': {
      id: '/api/akahu/callback'
      path: '/api/akahu/callback'
      fullPath: '/api/akahu/callback'
      preLoaderRoute: typeof ApiAkahuCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/akahu/oauth/start': {
      id: '/api/akahu/oauth/start'
      path: '/api/akahu/oauth/start'
      fullPath: '/api/akahu/oauth/start'
      preLoaderRoute: typeof ApiAkahuOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppActivityRoute: typeof AppActivityRoute
  AppNetWorthRoute: typeof AppNetWorthRoute
  AppPinboardRoute: typeof AppPinboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpendingRoute: typeof AppSpendingRoute
  AppWorkshopRoute: typeof AppWorkshopRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppActivityRoute: AppActivityRoute,
  AppNetWorthRoute: AppNetWorthRoute,
  AppPinboardRoute: AppPinboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSpendingRoute: AppSpendingRoute,
  AppWorkshopRoute: AppWorkshopRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DemoRouteChildren {
  DemoAccountsRoute: typeof DemoAccountsRoute
  DemoActivityRoute: typeof DemoActivityRoute
  DemoNetWorthRoute: typeof DemoNetWorthRoute
  DemoSpendingRoute: typeof DemoSpendingRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAccountsRoute: DemoAccountsRoute,
  DemoActivityRoute: DemoActivityRoute,
  DemoNetWorthRoute: DemoNetWorthRoute,
  DemoSpendingRoute: DemoSpendingRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface SigninRouteChildren {
  SigninPasswordRoute: typeof SigninPasswordRoute
  SigninIndexRoute: typeof SigninIndexRoute
}

const SigninRouteChildren: SigninRouteChildren = {
  SigninPasswordRoute: SigninPasswordRoute,
  SigninIndexRoute: SigninIndexRoute,
}

const SigninRouteWithChildren =
  SigninRoute._addFileChildren(SigninRouteChildren)

interface SignupRouteChildren {
  SignupCredentialRoute: typeof SignupCredentialRoute
  SignupNameRoute: typeof SignupNameRoute
  SignupPasswordRoute: typeof SignupPasswordRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupCredentialRoute: SignupCredentialRoute,
  SignupNameRoute: SignupNameRoute,
  SignupPasswordRoute: SignupPasswordRoute,
  SignupIndexRoute: SignupIndexRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceSplatRoute: typeof WorkspaceSplatRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceSplatRoute: WorkspaceSplatRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  DocsRoute: DocsRoute,
  HelpRoute: HelpRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SigninRoute: SigninRouteWithChildren,
  SignupRoute: SignupRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  ApiAkahuCallbackRoute: ApiAkahuCallbackRoute,
  ApiAkahuOauthStartRoute: ApiAkahuOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
